'use client';

import React, { useState, useRef } from 'react';
import { FileSearch, Upload, Trash2, Copy, Check, FileOutput } from 'lucide-react';

interface ChunkData {
  type: string;
  length: number;
  data: string;
}

export default function PngMetadataExtractorPage() {
  const [chunks, setChunks] = useState<ChunkData[]>([]);
  const [fileName, setFileName] = useState<string>('');
  const [error, setError] = useState<string>('');
  const [copiedIndex, setCopiedIndex] = useState<number | null>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);

  const parsePNG = (buffer: ArrayBuffer) => {
    const bytes = new Uint8Array(buffer);
    const dataView = new DataView(buffer);
    
    // PNG signature check
    const signature = [0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A];
    for (let i = 0; i < 8; i++) {
      if (bytes[i] !== signature[i]) {
        throw new Error("Not a valid PNG file");
      }
    }

    let offset = 8;
    const nonImageChunks: ChunkData[] = [];

    while (offset < bytes.length) {
      if (offset + 8 > bytes.length) break;

      const length = dataView.getUint32(offset);
      offset += 4;
      
      const typeBytes = bytes.slice(offset, offset + 4);
      const typeStr = String.fromCharCode(...typeBytes);
      offset += 4;

      const endOffset = offset + length;
      if (endOffset > bytes.length) break;
      
      const chunkData = bytes.slice(offset, endOffset);
      offset += length;
      offset += 4; // Skip CRC

      if (typeStr !== 'IHDR' && typeStr !== 'IDAT') {
        let decoded = '';
        try {
          const textDecoder = new TextDecoder('utf-8', { fatal: true });
          decoded = textDecoder.decode(chunkData);
        } catch (e) {
          // Fallback to hex
          decoded = Array.from(chunkData).map(b => b.toString(16).padStart(2, '0')).join('');
        }

        nonImageChunks.push({
          type: typeStr,
          length: length,
          data: decoded
        });
      }

      if (typeStr === 'IEND') {
        break;
      }
    }

    return nonImageChunks;
  };

  const handleFileUpload = (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (!file) return;

    setFileName(file.name);
    setError('');
    setChunks([]);

    const reader = new FileReader();
    reader.onload = (e) => {
      const buffer = e.target?.result;
      if (buffer instanceof ArrayBuffer) {
        try {
          const extracted = parsePNG(buffer);
          setChunks(extracted);
        } catch (err: any) {
          setError(err.message || 'Failed to parse image');
        }
      }
    };
    reader.onerror = () => {
      setError("Failed to read file.");
    };
    reader.readAsArrayBuffer(file);
    
    if (fileInputRef.current) {
        fileInputRef.current.value = '';
    }
  };

  const clearData = () => {
    setChunks([]);
    setFileName('');
    setError('');
  };

  const copyToClipboard = (text: string, index: number) => {
    navigator.clipboard.writeText(text);
    setCopiedIndex(index);
    setTimeout(() => setCopiedIndex(null), 2000);
  };

  return (
    <div className="flex flex-col min-h-[calc(100vh-4rem)] max-w-5xl mx-auto w-full p-4 sm:p-6 lg:p-8">
      <div className="mb-8 shrink-0">
        <h1 className="text-3xl font-bold text-gray-900 flex items-center gap-3">
          <FileSearch className="w-8 h-8 text-indigo-600" />
          PNG Metadata Extractor
        </h1>
        <p className="text-gray-500 text-base mt-2">
          Extract text, prompts, and config details embedded in PNG files generated by AI tools like Stable Diffusion.
        </p>
      </div>

      <div className="flex flex-col gap-6 w-full">
        {/* Upload Section */}
        <div className="bg-white rounded-2xl shadow-sm border border-gray-200 overflow-hidden">
          <div className="p-6 md:p-8">
            <div 
               className={`border-2 border-dashed rounded-xl p-8 flex flex-col items-center justify-center transition-colors ${fileName ? 'border-indigo-200 bg-indigo-50/30' : 'border-gray-300 bg-gray-50 hover:bg-gray-100 hover:border-gray-400'}`}
               onDragOver={(e) => e.preventDefault()}
               onDrop={(e) => {
                   e.preventDefault();
                   if (e.dataTransfer.files && e.dataTransfer.files.length > 0) {
                     const file = e.dataTransfer.files[0];
                     if(fileInputRef.current) {
                         const dataTransfer = new DataTransfer();
                         dataTransfer.items.add(file);
                         fileInputRef.current.files = dataTransfer.files;
                         
                         const event = new Event('change', { bubbles: true });
                         fileInputRef.current.dispatchEvent(event);
                     }
                   }
               }}
            >
              <FileSearch className={`w-12 h-12 mb-4 ${fileName ? 'text-indigo-500' : 'text-gray-400'}`} />
              <input
                type="file"
                accept="image/png"
                className="hidden"
                ref={fileInputRef}
                onChange={handleFileUpload}
              />
              
              {fileName ? (
                 <div className="text-center">
                    <p className="text-sm font-semibold text-gray-800 mb-1">Current file: {fileName}</p>
                    <div className="flex items-center gap-3 mt-4">
                       <button
                         onClick={() => fileInputRef.current?.click()}
                         className="px-4 py-2 bg-white border border-gray-300 rounded-lg text-sm font-medium text-gray-700 hover:bg-gray-50 transition-colors shadow-sm"
                       >
                         Choose Another
                       </button>
                       <button
                         onClick={clearData}
                         className="px-4 py-2 bg-red-50 text-red-600 rounded-lg text-sm font-medium hover:bg-red-100 transition-colors"
                       >
                         Clear
                       </button>
                    </div>
                 </div>
              ) : (
                 <div className="text-center">
                    <button
                      onClick={() => fileInputRef.current?.click()}
                      className="px-6 py-2.5 bg-indigo-600 text-white rounded-xl font-medium hover:bg-indigo-700 transition-colors shadow-sm mb-3"
                    >
                      Select PNG file
                    </button>
                    <p className="text-sm text-gray-500">or drop a file here</p>
                 </div>
              )}
            </div>
            
            {error && (
              <div className="mt-4 p-4 bg-red-50 border border-red-200 rounded-xl text-red-600 text-sm font-medium">
                {error}
              </div>
            )}
          </div>
        </div>

        {/* Results Section */}
        {chunks.length > 0 && (
          <div className="bg-white rounded-2xl shadow-sm border border-indigo-200 overflow-hidden flex flex-col">
            <div className="bg-gradient-to-r from-indigo-50 to-white px-6 py-4 border-b border-indigo-100 flex justify-between items-center">
              <div>
                <span className="font-semibold text-base text-indigo-900 flex items-center gap-2">
                  <FileOutput className="w-5 h-5" />
                  Extracted Metadata
                </span>
                <p className="text-sm text-indigo-600 mt-1">Found {chunks.length} non-image chunk(s)</p>
              </div>
            </div>
            
            <div className="p-6 bg-gray-50/50 flex flex-col gap-6">
              {chunks.map((chunk, index) => (
                <div key={index} className="flex flex-col bg-white border border-gray-200 rounded-xl overflow-hidden shadow-sm hover:border-indigo-300 transition-all">
                  <div className="flex items-center justify-between px-4 py-3 bg-gray-50 border-b border-gray-200">
                     <div className="flex items-center gap-3">
                        <span className="inline-flex items-center justify-center bg-indigo-100 text-indigo-700 w-6 h-6 rounded-md text-xs font-bold">
                           #{index + 1}
                        </span>
                        <span className="text-sm font-semibold text-gray-800 tracking-wide">
                          Type: <span className="text-indigo-600 ml-1">{chunk.type}</span>
                        </span>
                        <span className="text-xs text-gray-500 font-medium bg-gray-200/50 px-2 py-1 rounded-md">
                          Size: {chunk.length} bytes
                        </span>
                     </div>
                     <button
                        onClick={() => copyToClipboard(chunk.data, index)}
                        className="flex items-center gap-1.5 px-3 py-1.5 bg-white border border-gray-200 text-gray-600 rounded-lg hover:bg-gray-50 transition-colors text-xs font-medium shadow-sm"
                      >
                        {copiedIndex === index ? (
                          <><Check className="w-3.5 h-3.5 text-green-500" /> Copied</>
                        ) : (
                          <><Copy className="w-3.5 h-3.5" /> Copy Data</>
                        )}
                      </button>
                  </div>
                  <div className="p-4 overflow-auto max-h-[400px]">
                     <pre className="font-mono text-sm text-gray-800 whitespace-pre-wrap break-all">
                       {chunk.data.replace(/\0/g, ' ')}
                     </pre>
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
